name: Verify pull request base branch

on:
  pull_request:
    branches:
      - main

jobs:
  verify-base-branch:
    name: Verify base branch is staging
    runs-on: ubuntu-18.04
    steps:
      - name: Check base branch
        if: github.head_ref != 'staging'
        run: exit 1
